### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by joukeHijlkema** [tomojitakasu/RTKLIB#209]
Hello all,

I have a problem compiling the latest rtklib_2.4.3 branch 

> hylkema@grotte:/Software/RTKLIB$ git status -b
> On branch rtklib_2.4.3
> Your branch is up-to-date with 'origin/rtklib_2.4.3'.

after running make qmake and make I have the following error 

> svrmain.cpp: In member function ‘void MainForm::SvrStart()’:
> svrmain.cpp:599:60: error: cannot convert ‘char*’ to ‘char**’ for argument ‘6’ to ‘int strsvrstart(strsvr_t*, int*, int*, char**, strconv_t**, char**, const double*)’
>      if (!strsvrstart(&strsvr,opt,strs,paths,conv,cmd,AntPos)) return;
>                                                             ^
> svrmain.cpp: In member function ‘void MainForm::SvrStop()’:
> svrmain.cpp:623:27: error: cannot convert ‘char*’ to ‘char**’ for argument ‘2’ to ‘void strsvrstop(strsvr_t*, char**)’
>      strsvrstop(&strsvr,cmd);

This seems logical since strsvrstart is declared as

> extern int strsvrstart(strsvr_t *svr, int *opts, int *strs, char **paths,
>                        strconv_t **conv, char **cmds, const double *nmeapos)

and in svrmain.cpp cmd is declared as

>  char cmd[1024];

Am I missing something or is this a bug ?

Jouke

**Comment by tomojitakasu** [comment]
The API strsvrstart() and strsvrstop() are changed in 2.4.3 b15.

**Comment by jbeilin** [comment]
Hello, 

I do not know if I am doing something wrong but I have the same kind of problem. When I try to compile Rtklib_qt I have to change 2 headers :

EXPORT int  strsvrstart(strsvr_t *svr, int *opts, int *strs, char
    **paths, strconv_t **conv, char *cmds, const double *nmeapos);
EXPORT void strsvrstop (strsvr_t *svr, char *cmds);

I have to put *cmds instead of **cmds in order to build. 

I work on Ubuntu 16.04 with Qt5.5.1. With this modification rtklib works fine ! And It is great to have a GUI for rtklib on Linux !
