### ISSUE TITLE
Launch rtkrcv at boot of my Linux system

### ISSUE THREAD

**Issue by afermi** [tomojitakasu/RTKLIB#298]
Hello,
I need to launch rtkrcv at boot of my system with Linux/Debian OS. In order to do that I wrote a bash file containing the following call

rtkrcv -s -o "my_conf_file.conf"

and created the Linux service with update-rc.d. However rtkrcv is not executed. 
Have anyone had a similar problem? Any hint how to solve it?

Thank you very much,
Alessandro

**Comment by rob-brough** [comment]
I have the same problem under Debian 8. It appears to be due to the segmentation fault error, a result of the b24 release apparently.

The problem is crudely solved by starting rtkrcv manually ("rtkrcv -o my_conf_file.conf" and then "start").
I haven't figured out how to write this into a script yet, so I too am looking for a solution!

**Comment by MrYuJing** [comment]
I meet the same problem too. If I turn on outstream into a file in the configure file and then excute "rtkrcv -s -o "my_conf_file.conf" " in my putty terminal, but the terminal immediately closed  and I found rtkrcv was not running at backend using "top" command in a new  terminal. On the other side, if I turn off outstream into a file in the configure file and then excute "rtkrcv -s -o "my_conf_file.conf" " in my putty terminal, everything is ok. I hope this phenomenon will be a little clue to find out reason.

**Comment by Rjbsnxt** [comment]
Yes I found that too MrYuLing - outputting to a file was the problem.

**Comment by billmaidment** [comment]
Hi. I have a similar problem, but it is with 2.4.2p12. According to the logs it appears that my /etc/rc.local is not completing. It seems to stop partway through the nvsmode instruction on boot.
(/bin/sleep 5 && /usr/bin/nvsctl -v reset)
(/bin/sleep 7 && /usr/bin/nvsmode -v binr)
(/bin/sleep 9 && /usr/bin/binrcmd -v /home/pi/rtk/init.cmd)
(/bin/sleep 11 && /usr/bin/rtkrcv -s -o /home/pi/rtk/rtkrover.conf &)
However, running these instructions manually competes OK.
This may not be the same problem, or it may be a pointer to the source of the problem.
Interestingly, the same setup on the base machine, with the final line:
(/bin/sleep 11 && /usr/bin/rtkbase &)
is working OK on boot.
nvsmode script attached as nvsmode.txt
[nvsmode.txt](https://github.com/tomojitakasu/RTKLIB/files/1117690/nvsmode.txt)

**Comment by sezeryalcin** [comment]
This is a duplicate of https://github.com/tomojitakasu/RTKLIB/issues/272
Please close this bug and add comments on main bug. No need confusion.
Also as we have p26 now, nobody will fix issues at p12. So upgrade to never version and test.

**Comment by billmaidment** [comment]
Hi all

I don't see 2.4.2p26 on github. Or do you mean 2.4.3b26 ?
Anyway, is 2.4.2 still supported? If not, then 2.4.3 ought to come out of Beta.
I'm nor sure what is the stable supported release now.

Cheers
Bill 
 
-----Original message-----

**Comment by sezeryalcin** [comment]
Sorry, its b26, not p26.
2.4.3 is still beta and there is no problem with using 2.4.2. However, if you are using beta version, you should try newer version.

**Comment by billmaidment** [comment]
OK. No worries.
However, I tried 2.4.3b28 with the suggested fix and I still don't get an autostart at boot (without -s), but a manual start (without -s) works. It just seems that rtkrcv dies even before it open the trace file (or maybe it's when it opens the trace file).
I'll do some more debugging to see if I can uncover more detail.

Cheers
Bill
 
-----Original message-----

**Comment by sezeryalcin** [comment]
This fix works for me with b27. I had several compilation errors with b28 and use b27.
This is on raspberry pi with raspbian (debian jessie mod)
You must do make clean and recompile with make in RTKLIB_2.4.3/app/rtkrcv/gcc folder.

**Comment by billmaidment** [comment]
Thanks for the suggestions:
1. I did make clean and make on b28 using your makefile amendments from issue #306 with only a few warning messages.
2. I have a similar setup to you RasPi 3B with Raspbian Jessie and I have a RaspiGNSS module.
3. The issue I have appears in 2.4.2p12 and 2.4.3b28 and seems to be a systemd timing problem, where the drivers have not all been installed when rtkrcv is started.
4. I don't yet know enough about Git to get b27. But I will learn.
5. I started rtkrcv in /etc/rc.local, but that was a bad choice, so I will try auto-starting it after login (in ~/.config/autostart I believe).

Conclusion.
This is not an issue with the rtkrcv code.
 
-----Original message-----

**Comment by billmaidment** [comment]
Hi Again
I take back all my comments about a systemd timing issues. That turned out was not the case.

What I did find out from adding to the beginning of /etc/rc.local
exec > /tmp/rc-local.log 2>&1
was that I was getting an error message from rtkrcv ONLY WHEN STARTED IN /etc/rc.local, which indicated I must have a -d option defining the console device.
I added -d /dev/tty0 to my rtkrcv command in /etc/rc.local and it now works OK in 2.4.3b28

Maybe this should be documented somewhere. My apologies if it is and I missed it.
Cheers
Bill
 
 
-----Original message-----

**Comment by windsoryin** [comment]
> 
Hi billmaidment, Thanks for your post. I solved similar problems in my trying to auto-start RTKRCV. It really save my day!
